// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzKRyOT6mATRgWqRmtFpRKkNq9tD9NiBQ',
    appId: '1:203325071131:web:68dc845696e9b31d95fdbe',
    messagingSenderId: '203325071131',
    projectId: 'crud-firebase-1a8f9',
    authDomain: 'crud-firebase-1a8f9.firebaseapp.com',
    storageBucket: 'crud-firebase-1a8f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS5eVWvcjy5aJXeqb-LmhNH3sR-G0aMPw',
    appId: '1:203325071131:android:f22a51dd403de3b995fdbe',
    messagingSenderId: '203325071131',
    projectId: 'crud-firebase-1a8f9',
    storageBucket: 'crud-firebase-1a8f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrrBqrS47V2DTAnS85S-pIQ927pWt6B2I',
    appId: '1:203325071131:ios:fa0da38ce077a0a795fdbe',
    messagingSenderId: '203325071131',
    projectId: 'crud-firebase-1a8f9',
    storageBucket: 'crud-firebase-1a8f9.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrrBqrS47V2DTAnS85S-pIQ927pWt6B2I',
    appId: '1:203325071131:ios:fb479d698da7eca495fdbe',
    messagingSenderId: '203325071131',
    projectId: 'crud-firebase-1a8f9',
    storageBucket: 'crud-firebase-1a8f9.appspot.com',
    iosBundleId: 'com.example.crudFirebase.RunnerTests',
  );
}
